[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "spacetime"
authors = [{name = "Robot", email = "robot@keshav.space"}]
dynamic = ["version", "description"]
